[bot]
token = ""

[storage] # (Optional) Persistent FSM Storage for aiogram and aiogram_dialog, disabled by default
use_persistent_storage = false # (Optional)
# redis_url = "redis://user:password@host:port/db" # (Optional) Redis URL for FSM storage

[webhook] # (Optional) Settings for Webhook, disabled by default
port = 80
url = "" # (Optional) Webhook URL
path = "" # (Optional) Webhook URL path

[settings]
owner_id = 
currency_token = "" # currencyapi.net
use_webhook = false # (Optional)
drop_pending_updates = false
